ablation_frac: 0.5
dt: 0.001
e_i_max_val: 0.05
e_i_precent_conn: 0.5
e_i_tailed_dist: true
i_e_max_val: -0.1
i_e_precent_conn: 0.5
i_e_tailed_dist: true
i_i_max_val: -1
i_i_precent_conn: 0.05
i_i_tailed_dist: true
lesion_bars: false
lesion_e: true
lesion_i: true
num_eigsum: 10
num_exc_neur: 90
num_inh_neur: 10
probe_synapse: 0.05
sim_duration: 4
t_bin: 20
time_cut_off: 4000
